### ISSUE TITLE
Error in RandomMaze 

### ISSUE THREAD

**Issue by msun2019** [Pingry-Java/MazeSolver#15] opened 2017-05-24 13:15 UTC
i got an error when i initialized a size 15 random maze and tried to solve it using depthfirstmazesolver

**Comment by jorndorff** [comment] 2017-05-24 13:25
I'm curious whether the problem is in `RandomMaze` or `DepthFirstMazeSolver`. Are you able to solve the same maze with any other solver?

Let's get this assigned to someone from Generation group and Solution group.

**Comment by drew-beckmen** [comment] 2017-05-25 18:18
fixed

**Closed as completed by drew-beckmen** 2017-05-25 18:18 UTC
